name: duzify
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 
  http: 
  google_fonts: 
  flutter_svg: 
  hydrated_bloc: 
  path_provider: 
  dartz: 
  get_it: 
  flutter_bloc: 
  async: ^2.11.0
  marquee: ^2.3.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/vectors/

  fonts:
    - family: HelveticaNeue
      fonts:
        - asset: assets/fonts/HelveticaNeueBlack.otf
          weight: 900
        - asset: assets/fonts/HelveticaNeueHeavy.otf
          weight: 700
        - asset: assets/fonts/HelveticaNeueBold.otf
          weight: 600
        - asset: assets/fonts/HelveticaNeueMedium.otf
          weight: 500
        - asset: assets/fonts/HelveticaNeueRoman.otf
          weight: 400
        - asset: assets/fonts/HelveticaNeueLight.otf
          weight: 300
        - asset: assets/fonts/HelveticaNeueThin.otf
          weight: 200
        - asset: assets/fonts/HelveticaNeueUltraLight.otf
          weight: 100
